"""
Django settings for blablaUCM project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: v.split(','))

ALLOWED_DOMAINS = config('ALLOWED_DOMAINS',default='*',cast=lambda v: [d.strip().lower().lstrip('@') for d in v.split(',') if d.strip()])

# Con True se aceptan peticiones de cualquier origen y CORS_ALLOWED_ORIGINS queda ignorada
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)

# Ruta del panel de administracion. En /admin/ queda un señuelo asi que el panel real tiene que estar en otro sitio 
ADMIN_URL = config('ADMIN_URL', default='panel-interno/')

# Se normaliza para que valga tanto "panel/" como "/panel" o "panel"
ADMIN_URL = ADMIN_URL.strip('/') + '/'

# Si el panel se quedara en /admin/ chocaria con el señuelo y una de las dos
# rutas se solapa con la otra, por lo que no se permite tener ambas en /admin/
if ADMIN_URL == 'admin/':
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "ADMIN_URL no puede ser 'admin/': esa ruta la ocupa el señuelo. "
        "Elige otra en el .env."
    )

# Application definition

INSTALLED_APPS = [
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'channels',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    'users.apps.UsersConfig',
    'django.contrib.gis',

    'travels',
    'chats',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware',
]

ROOT_URLCONF = 'blablaUCM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Plantillas del proyecto que no pertenecen a ninguna app
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blablaUCM.wsgi.application'

ASGI_APPLICATION = 'blablaUCM.asgi.application'

REDIS_URL = config('REDIS_URL', default='')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }

# La limitacion de peticiones lleva su cuenta en la cache, asi que la cache tiene
# que ser compartida entre procesos, por lo que es necesario usar Redis
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else: # Sin Redis, la cache es local y se usa un solo proceso
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'blablaucm-local',
        }
    }


# Limitacion de peticiones de los endpoints abiertos, se desactiva con THROTTLE_ENABLED=False
THROTTLE_ENABLED = config('THROTTLE_ENABLED', cast=bool, default=True)

REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": (
        "api.authentication.UsersJWTAuthentication",
    ),

    # Un unico formato de error para toda la API
    "EXCEPTION_HANDLER": "api.exception_handler.unified_exception_handler",

    # Solo actua sobre las vistas que declaran throttle_scope
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.ScopedRateThrottle",
    ),

    # Numero de proxies de confianza entre el cliente y esta aplicacion
    # Si solo se utiliza Caddy, hay que poner NUM_PROXIES=1, si se ponen mas hay que ajustarlo
    "NUM_PROXIES": config('NUM_PROXIES', default=1, cast=int),

    "DEFAULT_THROTTLE_RATES": {
        # Envio del codigo de verificacion al correo de la cuenta
        "verification_email": config('THROTTLE_VERIFICATION_EMAIL', default='5/hour') if THROTTLE_ENABLED else None,
        # Comprobacion del codigo, limita el probar codigos a lo bruto
        "verify_code": config('THROTTLE_VERIFY_CODE', default='10/hour') if THROTTLE_ENABLED else None,
        # Limite de peticiones de segundo factor
        "two_factor": config('THROTTLE_TWO_FACTOR', default='10/hour') if THROTTLE_ENABLED else None,
        # Consultas de existe este usuario / correo, limita la enumeracion
        "user_lookup": config('THROTTLE_USER_LOOKUP', default='30/hour') if THROTTLE_ENABLED else None,
        # Inicio de sesion, es la puerta de entrada y no tenia ningun limite
        "login": config('THROTTLE_LOGIN', default='10/minute') if THROTTLE_ENABLED else None,
        # Limite de peticiones de validacion de codigo de verificacion
        "validation_code": config('THROTTLE_VALIDATION_CODE', default='20/minute') if THROTTLE_ENABLED else None,
        # Limite de peticiones de entrada y alta con un proveedor externo (Google)
        "oauth_login": config('THROTTLE_OAUTH_LOGIN', default='20/minute') if THROTTLE_ENABLED else None,
        # Limite de peticiones de alta con usuario y contraseña
        "register": config('THROTTLE_REGISTER', default='10/hour') if THROTTLE_ENABLED else None,
        # limite de peticiones de refresco de token
        "token_refresh": config('THROTTLE_TOKEN_REFRESH', default='60/hour') if THROTTLE_ENABLED else None,
    },

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ],

    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",

    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

# Valores para proteger la documentacion de la API, solo los administradores pueden verla
SPECTACULAR_SETTINGS = {
    'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAdminUser'],
    'SERVE_AUTHENTICATION': ['rest_framework.authentication.SessionAuthentication'],
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://localhost:8000,http://127.0.0.1:3000,http://127.0.0.1:8000',
    cast=lambda v: v.split(',')
)

CORS_ALLOW_CREDENTIALS = True

# Origenes en los que Django se fia de la cookie CSRF
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='',
    cast=lambda v: [o.strip() for o in v.split(',') if o.strip()]
)

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

# Plazo maximo para hablar con el servidor de correo, sin esto, puede bloquearse el proceso indefinidamente
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)

# Email al que se avisa, si esta vacio, no se manda ningun correo, solo se registra en el log
HONEYPOT_NOTIFY_EMAIL = config('HONEYPOT_NOTIFY_EMAIL', default=EMAIL_HOST_USER)

# Limite de tiempo entre avisos de la misma IP
HONEYPOT_EMAIL_COOLDOWN = config('HONEYPOT_EMAIL_COOLDOWN', default=3600, cast=int)

# Limite global de avisos por hora, para no saturar el correo ante muchos bots
HONEYPOT_MAX_EMAILS_HOUR = config('HONEYPOT_MAX_EMAILS_HOUR', default=20, cast=int)

# Por defecto solo se notifica con un POST, si se pone a True, se notifica tambien al acceder a la pagina
HONEYPOT_NOTIFY_ON_GET = config('HONEYPOT_NOTIFY_ON_GET', default=False, cast=bool)


DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE'),
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        # Reutilizar la conexion entre peticiones
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=0, cast=int),
    }
}

# Modo TLS contra la BBDD
DB_SSLMODE = config('DB_SSLMODE', default='')
if DB_SSLMODE:
    DATABASES['default']['OPTIONS'] = {'sslmode': DB_SSLMODE}

DB_TEST_TEMPLATE = config('DB_TEST_TEMPLATE', default='')
if DB_TEST_TEMPLATE:
    DATABASES['default']['TEST'] = {'TEMPLATE': DB_TEST_TEMPLATE}

# Salida de los tests en formato JUnit XML
TEST_OUTPUT_DIR = config('TEST_OUTPUT_DIR', default='test-results')
TEST_OUTPUT_FILE_NAME = config('TEST_OUTPUT_FILE_NAME', default='junit.xml')
TEST_OUTPUT_VERBOSE = config('TEST_OUTPUT_VERBOSE', default=1, cast=int)


MEDIA_ROOT = os.path.join(BASE_DIR, config('MEDIA_PATH', default='media'))


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 6},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# HTTPS/SSL Settings for Production
# These are disabled by default for development, enable in production via .env
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)

SECURE_CSP = {
    "default-src": ["'self'"],
    "style-src": ["'self'", "'unsafe-inline'"],
    "script-src": ["'self'", "'unsafe-inline'"],
    "img-src": ["'self'", "data:"],
}
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=config('ACCESS_TOKEN_LIFETIME', default=1, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('REFRESH_TOKEN_LIFETIME', default=7, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JTI_CLAIM': 'jti',
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_URL_ARGUMENT_NAME': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=config('SLIDING_TOKEN_LIFETIME', default=5, cast=int)),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=config('SLIDING_TOKEN_REFRESH_LIFETIME', default=7, cast=int)),
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'AUTH_REFRESH_CLASSES': ('rest_framework_simplejwt.tokens.RefreshToken',),
    'AUTH_COOKIE': None,
    'AUTH_COOKIE_DOMAIN': None,
    'AUTH_COOKIE_SECURE': config('SESSION_COOKIE_SECURE', default=False, cast=bool),
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_PATH': '/',
    'AUTH_COOKIE_SAMESITE': 'Lax',

    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=config('SLIDING_TOKEN_LIFETIME', default=5, cast=int)),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=config('SLIDING_TOKEN_REFRESH_LIFETIME', default=7, cast=int)),
}

# Logging configuration
LOGS_PATH = config('LOGS_PATH', default=BASE_DIR / 'logs')
LOGS_NAME = config('LOGS_NAME', default='BlaBlaUCM')

# El directorio puede no existir en una nueva instalacion
os.makedirs(LOGS_PATH, exist_ok=True)

# Nivel de registro
LOG_LEVEL = config('LOG_LEVEL', default='DEBUG')

# Tamaño maximo de cada fichero y cuantos historicos se guardan
LOG_MAX_BYTES = config('LOG_MAX_BYTES', default=10 * 1024 * 1024, cast=int)
LOG_BACKUP_COUNT = config('LOG_BACKUP_COUNT', default=10, cast=int)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_PATH, f'{LOGS_NAME}.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['file'],
        'level': LOG_LEVEL,
    },
}

if os.name == 'nt':
    OSGEO4W_DIR = config('OSGEO4W_DIR')

    GDAL_LIBRARY_PATH = os.path.join(OSGEO4W_DIR, config('GDAL_DLL', default=r"bin\gdal312.dll"))
    GEOS_LIBRARY_PATH = os.path.join(OSGEO4W_DIR, config('GEOS_DLL', default=r"bin\geos_c.dll"))

    os.environ['PATH'] = os.path.join(OSGEO4W_DIR, "bin") + ";" + os.environ['PATH']
