# Generated by Django 6.0.3 on 2026-04-04 12:53

import django.core.validators
import django.db.models.deletion
import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(db_column='id_user', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('surname1', models.CharField(max_length=50)),
                ('surname2', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=users.models.user_profile_path, validators=[users.models.validate_image, users.models.validate_size])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'criteria',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_active_criteria_code')],
            },
        ),
        migrations.CreateModel(
            name='EnvTypes',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'env_types',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_active_env_code')],
            },
        ),
        migrations.CreateModel(
            name='PrefTypes',
            fields=[
                ('id_pref', models.AutoField(db_column='id_pref', editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pref_types',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_active_pref_types_code')],
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id_pref', models.UUIDField(db_column='id_pref', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pref_type', models.ForeignKey(db_column='pref_type', on_delete=django.db.models.deletion.CASCADE, to='users.preftypes')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='users.users')),
            ],
            options={
                'db_table': 'preferences',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.users')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='DriverRatings',
            fields=[
                ('id_rating', models.UUIDField(db_column='id_rating', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('criteria', models.ForeignKey(db_column='criteria', on_delete=django.db.models.deletion.CASCADE, to='users.criteria')),
                ('id_driver', models.ForeignKey(db_column='id_driver', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='users.users')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='users.users')),
            ],
            options={
                'db_table': 'driver_ratings',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id_type', models.AutoField(db_column='id_type', editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_type',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_active_user_type_code')],
            },
        ),
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.ForeignKey(db_column='user_type', on_delete=django.db.models.deletion.PROTECT, to='users.usertype'),
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id_vehicle', models.UUIDField(db_column='id_vehicle', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(max_length=20)),
                ('seats', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('env_sticker', models.ForeignKey(db_column='env_sticker', on_delete=django.db.models.deletion.CASCADE, to='users.envtypes')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.users')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('username',), name='unique_active_username'),
        ),
        migrations.AddConstraint(
            model_name='vehicles',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('license_plate',), name='unique_active_license_plate'),
        ),
    ]
