# Generated by Django 6.0.3 on 2026-04-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE OR REPLACE FUNCTION public.getdriverratings(user_identifier uuid)
            RETURNS TABLE(code character varying, avg_score numeric, num_ratings numeric)
            LANGUAGE plpgsql
            AS $function$
            BEGIN
                RETURN QUERY
                SELECT criteria, ROUND(AVG(score), 1), COUNT(*)::numeric
                FROM public.driver_ratings
                WHERE id_driver = user_identifier
                GROUP BY criteria;
            END;
            $function$
            ;
        """)
    ]
