# Generated by Django 6.0.3 on 2026-04-04 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driver_ratings_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverratings',
            name='criteria',
            field=models.ForeignKey(db_column='criteria', on_delete=django.db.models.deletion.CASCADE, to='users.criteria', to_field='code'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='pref_type',
            field=models.ForeignKey(db_column='pref_type', on_delete=django.db.models.deletion.CASCADE, to='users.preftypes', to_field='code'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.ForeignKey(db_column='user_type', on_delete=django.db.models.deletion.PROTECT, to='users.usertype', to_field='code'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='env_sticker',
            field=models.ForeignKey(db_column='env_sticker', on_delete=django.db.models.deletion.CASCADE, to='users.envtypes', to_field='code'),
        ),
    ]
