# Generated by Django 6.0.3 on 2026-04-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_driverratings_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
