# Generated by Django 6.0.3 on 2026-04-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_is_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='has_2FA',
            field=models.BooleanField(default=True),
        ),
    ]
