# Generated by Django 6.0.3 on 2026-05-26 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_email_alter_users_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='env_sticker',
            field=models.ForeignKey(db_column='env_sticker', on_delete=django.db.models.deletion.PROTECT, to='users.envtypes', to_field='code'),
        ),
    ]
