# Generated by Django 6.0.3 on 2026-06-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_vehicles_env_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='content',
            field=models.CharField(max_length=450),
        ),
    ]
