# Generated by Django 6.0.3 on 2026-07-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_seed_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token_purpose',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
