# Generated by Django 6.0.3 on 2026-08-06 10:55

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_users_token_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_profile_path, validators=[users.models.validate_image, users.models.validate_size, users.models.validate_extension]),
        ),
    ]
