# Generated by Django 6.0.3 on 2026-08-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_users_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='sessions_epoch',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
