# Generated by Django 6.0.3 on 2026-04-13 18:59

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_driverratings_criteria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStates',
            fields=[
                ('id_state', models.AutoField(db_column='id_state', editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'request_states',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_active_request_state')],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id_travel', models.UUIDField(db_column='id_travel', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodic_interval', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('is_periodic', models.BooleanField(default=False)),
                ('end_periodic_date', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(max_length=175)),
                ('destination', models.CharField(max_length=175)),
                ('origin_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('destination_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('num_seats', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('remaining_seats', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('travel_date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('creation_user', models.ForeignKey(db_column='creation_user', on_delete=django.db.models.deletion.CASCADE, related_name='created_travels', to='users.users')),
                ('id_origin_travel', models.ForeignKey(blank=True, db_column='id_origin_travel', null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.travel')),
                ('vehicle', models.ForeignKey(db_column='vehicle', on_delete=django.db.models.deletion.PROTECT, to='users.vehicles')),
            ],
            options={
                'db_table': 'travel',
            },
        ),
        migrations.CreateModel(
            name='RequestTravels',
            fields=[
                ('id', models.UUIDField(db_column='id_request', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, to='travels.requeststates', to_field='code')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='requested_travels', to='users.users')),
                ('id_travel', models.ForeignKey(db_column='id_travel', on_delete=django.db.models.deletion.CASCADE, related_name='requested_travels', to='travels.travel')),
            ],
            options={
                'db_table': 'request_travels',
            },
        ),
        migrations.CreateModel(
            name='TravelStates',
            fields=[
                ('id_state', models.AutoField(db_column='id_state', editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'travel_states',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_active_travel_state')],
            },
        ),
        migrations.AddField(
            model_name='travel',
            name='state',
            field=models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.PROTECT, to='travels.travelstates', to_field='code'),
        ),
        migrations.CreateModel(
            name='UsersDenied',
            fields=[
                ('id_deny', models.UUIDField(db_column='id_deny', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_travel', models.ForeignKey(db_column='id_travel', on_delete=django.db.models.deletion.CASCADE, related_name='users_denied', to='travels.travel')),
                ('user_type', models.ForeignKey(db_column='user_type', on_delete=django.db.models.deletion.CASCADE, to='users.usertype', to_field='code')),
            ],
            options={
                'db_table': 'users_denied',
            },
        ),
        migrations.CreateModel(
            name='PickUpPoints',
            fields=[
                ('id_point', models.UUIDField(db_column='id_point', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=175)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('order_in_travel', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_travel', models.ForeignKey(db_column='id_travel', on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='travels.travel')),
            ],
            options={
                'db_table': 'pickup_points',
                'indexes': [models.Index(fields=['id_travel'], name='pickup_poin_id_trav_2c4ce2_idx')],
                'constraints': [models.UniqueConstraint(fields=('id_travel', 'order_in_travel'), name='unique_order_per_travel')],
            },
        ),
        migrations.AddIndex(
            model_name='travel',
            index=models.Index(fields=['travel_date'], name='travel_travel__363916_idx'),
        ),
        migrations.AddIndex(
            model_name='travel',
            index=models.Index(fields=['origin', 'destination'], name='travel_origin_1397c1_idx'),
        ),
    ]
