# Generated by Django 6.0.3 on 2026-04-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20260413_2100'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION public.sp_delete_travels()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                IF NEW.is_deleted = true AND OLD.is_deleted = false THEN
                    
                    UPDATE public.pickup_points SET is_deleted = true WHERE id_travel = NEW.id_travel;
                    UPDATE public.pickup_points SET deleted_at = NOW() WHERE id_travel = NEW.id_travel;
                    UPDATE public.users_denied SET is_deleted = true WHERE id_travel = NEW.id_travel;
                    UPDATE public.users_denied SET deleted_at = NOW() WHERE id_travel = NEW.id_travel;
                    
                END IF;
                RETURN NEW;
            END;
            $$;

            -- Trigger para ejecutar la funcion de soft delete en cascada de los roles y paradas
            CREATE TRIGGER trigger_sp_delete_travels
            AFTER UPDATE OF is_deleted ON public.travel
            FOR EACH ROW
            EXECUTE FUNCTION public.sp_delete_travels();
            """,
            reverse_sql="""
            -- Codigo para revertir la migración si hacemos un rollback
            DROP TRIGGER IF EXISTS trigger_sp_delete_travels ON public.travel;
            DROP FUNCTION IF EXISTS public.sp_delete_travels();
            """
        )
    ]
