# Generated by Django 6.0.3 on 2026-04-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_sp_delete_travels'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION public.create_periodic_travels()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $function$
            DECLARE
                start_date TIMESTAMPTZ := NEW.travel_date;
                end_date DATE := NEW.end_periodic_date;
                next_date TIMESTAMPTZ;
            BEGIN
                -- Solo actuar si el viaje es periódico, los puntuales no hace falta crear nada (solo hay uno)
                IF NEW.is_periodic = true 
                   AND NEW.periodic_interval > 0 
                   AND NEW.id_origin_travel IS NULL  -- Para no crear nuevos viajes cuando se cambie de estado (eso se hace en django)
                   AND NEW.end_periodic_date IS NOT NULL THEN

                   -- Primer viaje generado: travel_date + intervalo (NO incluye el original)
                   next_date := start_date + make_interval(days => NEW.periodic_interval);

                   WHILE next_date::date <= end_date LOOP
                        INSERT INTO public.travel (
                            id_travel,
                            periodic_interval,
                            is_periodic,
                            origin,
                            destination,
                            duration_minutes,
                            num_seats,
                            remaining_seats,
                            travel_date,
                            is_deleted,
                            created_at,
                            updated_at,
                            deleted_at,
                            creation_user,
                            id_origin_travel,
                            vehicle,
                            state,
                            end_periodic_date,
                            destination_point,
                            origin_point
                        )
                        VALUES (
                            gen_random_uuid(),
                            NEW.periodic_interval,
                            true, 
                            NEW.origin,
                            NEW.destination,
                            NEW.duration_minutes,
                            NEW.num_seats,
                            NEW.num_seats,
                            next_date,
                            false,
                            NOW(),
                            NOW(),
                            NULL,
                            NEW.creation_user,
                            NEW.id_travel,
                            NEW.vehicle,
                            NEW.state,
                            NEW.end_periodic_date,
                            NEW.destination_point,
                            NEW.origin_point
                        );

                        next_date := next_date + make_interval(days => NEW.periodic_interval);
                    END LOOP;
                END IF;

                RETURN NEW;
            END;
            $function$;


            -- El Trigger para que se ejecute DESPUES de un INSERT en 'travel'
            DROP TRIGGER IF EXISTS trigger_generate_periodic_travels ON public.travel;
            CREATE TRIGGER trigger_generate_periodic_travels
            AFTER INSERT ON public.travel
            FOR EACH ROW
            EXECUTE FUNCTION public.create_periodic_travels();
            """,
            
            # Por si hay un rollback
            reverse_sql="""
            DROP TRIGGER IF EXISTS trigger_generate_periodic_travels ON public.travel;
            DROP FUNCTION IF EXISTS public.create_periodic_travels();
            """
        )
    ]