# Generated by Django 6.0.3 on 2026-04-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_sp_create_periodic_travels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='travel_date',
            field=models.DateTimeField(),
        ),
    ]
