# Generated by Django 6.0.3 on 2026-04-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_alter_travel_travel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoints',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
