# Generated by Django 6.0.3 on 2026-05-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_pickuppoints_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pickuppoints',
            name='unique_order_per_travel',
        ),
        migrations.AlterField(
            model_name='pickuppoints',
            name='direction',
            field=models.CharField(max_length=250),
        ),
        migrations.AddConstraint(
            model_name='pickuppoints',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('id_travel', 'order_in_travel'), name='unique_order_per_travel'),
        ),
    ]
