# Generated by Django 6.0.3 on 2026-05-26 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_remove_pickuppoints_unique_order_per_travel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='id_origin_travel',
            field=models.ForeignKey(blank=True, db_column='id_origin_travel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='travels.travel'),
        ),
    ]
