# Generated by Django 6.0.3 on 2026-05-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_alter_travel_id_origin_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttravels',
            name='validation_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
