# Generated by Django 6.0.3 on 2026-06-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_requesttravels_validation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoints',
            name='is_reached',
            field=models.BooleanField(default=False),
        ),
    ]
