# Generated by Django 6.0.3 on 2026-06-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_pickuppoints_is_reached'),
        ('users', '0007_alter_vehicles_env_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttravels',
            name='validation_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='requesttravels',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('validation_code__isnull', False)), fields=('id_travel', 'validation_code'), name='unique_code_per_travel'),
        ),
    ]
