# Clase con los errores que puede lanzar la API
class ErrorCodes:
    #Errores del usuario
    USER_DONT_EXIST=0
    EMAIL_ALREADY_EXISTS=1
    USERNAME_ALREADY_EXISTS=2
    USER_DELETED=3
    PASSWORD_MISMATCH = 5
    INVALID_CREDENTIALS=6
    INSUFICIENT_CREDENTIALS=7
    TOKEN_EXPIRED=8
    INCORRECT_TOKEN=9
    USER_NOT_VERIFIED=10
    EMAIL_ERROR=11
    
    #Errores del vehiculo
    LICENSE_PLATE_ALREADY_EXISTS=20
    LICENSE_PLAETE_TOO_LONG=21
    VEHICLE_ASSOCIATED_TO_TRAVEL=22
    VEHICLE_DONT_EXIST=23
    VEHICLE_SEATS_INSUFFICIENT=24
    
    #Errores del viaje
    TRAVEL_DONT_EXIST=30
    TRAVEL_ALREADY_DELETED=31
    TRAVEL_NOT_FOUND=32
    TRAVEL_ALREADY_EXISTS=33
    TRAVEL_IS_FULL=34
    TRAVEL_IS_NOT_PERIODIC=35
    TRAVEL_IS_NOT_PUNCTUAL=36
    FROM_DATE_REQUIRED=37
    TO_DATE_REQUIRED=38

