class ErrorCodes:
    #UserErrors
    USER_DONT_EXIST=0
    USER_ALREADY_EXISTS=1
    USER_DELETED=2
    PASSWORD_MISMATCH = 5
    INVALID_CREDENTIALS=6
    INSUFICIENT_CREDENTIALS=7
    #VehicleErrors
    LICENSE_PLATE_ALREADY_EXISTS=20
    LICENSE_PLAETE_TOO_LONG=21
