# Generated by Django 6.0.3 on 2026-07-12 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('users', '0009_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.UUIDField(db_column='id_membership', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_muted', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(db_column='id_chat', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chats.chat')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to='users.users')),
            ],
            options={
                'db_table': 'chat_membership',
                'constraints': [models.UniqueConstraint(fields=('chat', 'user'), name='unique_chat_membership_per_user')],
            },
        ),
    ]
