// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzwwz1oCK_rFRk92VNsP-XSt-o8TLMlw4',
    appId: '1:228270723178:web:d9382ca34ae9b46a107a13',
    messagingSenderId: '228270723178',
    projectId: 'blablaucm-b271a',
    authDomain: 'blablaucm-b271a.firebaseapp.com',
    storageBucket: 'blablaucm-b271a.firebasestorage.app',
    measurementId: 'G-GX0H6SGSM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN4TWI4zZi5xHjRK0nN8VamkNKXErAtJM',
    appId: '1:228270723178:android:bc1621366c1b02f9107a13',
    messagingSenderId: '228270723178',
    projectId: 'blablaucm-b271a',
    storageBucket: 'blablaucm-b271a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDViG3nMSwupwukoU0GJQplkSYpxSlzv4o',
    appId: '1:228270723178:ios:38996271d3715d14107a13',
    messagingSenderId: '228270723178',
    projectId: 'blablaucm-b271a',
    storageBucket: 'blablaucm-b271a.firebasestorage.app',
    iosBundleId: 'com.example.blablaucm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDViG3nMSwupwukoU0GJQplkSYpxSlzv4o',
    appId: '1:228270723178:ios:38996271d3715d14107a13',
    messagingSenderId: '228270723178',
    projectId: 'blablaucm-b271a',
    storageBucket: 'blablaucm-b271a.firebasestorage.app',
    iosBundleId: 'com.example.blablaucm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzwwz1oCK_rFRk92VNsP-XSt-o8TLMlw4',
    appId: '1:228270723178:web:9303882b9b3bb790107a13',
    messagingSenderId: '228270723178',
    projectId: 'blablaucm-b271a',
    authDomain: 'blablaucm-b271a.firebaseapp.com',
    storageBucket: 'blablaucm-b271a.firebasestorage.app',
    measurementId: 'G-LY2X3ECTP0',
  );
}
